service: rental-car

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-north-1

functions:
  swaggerUi:
    handler: dist/main.handler
    timeout: 30
    events:
      - http:
          path: "/api/{proxy+}"
          method: any
          cors: true
      - http: # Swagger UI endpoint
          path: "/{proxy+}/"
          method: any
          cors: true
          authorizer: null



plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
  optimize:
    external: ['swagger-ui-dist']

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - test/**
    - .gitignore
    - README.md
